import { Typography } from "@mui/material";

const msg = "Thank you for participating in the study. The study is about the emotion of awe. Have you ever seen a vast beautiful mountain which made you feel small? Or perhaps you read a book that humbled you, connected you to others and made you reassess your current life. That is awe! We experience awe usually when we come across vast things or complex ideas. It's an overwhelming emotion that makes us feel small and puts us in touch with bigger concerns. Research suggests that awe has various benefits in daily life like improved well-being, reduced stress and anxiety, increased prosocial behaviors and meaning in life. To read more about this please refer to the following link- https://journals.sagepub.com/doi/full/10.1177/17456916221094856. Some of you were presented with photos and some with narratives. This was done to compare the two methods on their ability to produce awe. Researchers in my field are in the midst of a debate regarding best practices to induce awe and this study helps contribute towards that end. My hypothesis is that both narratives and photos would be equally good at producing awe since both have certain unique features which induce intense emotions. You were not informed about this purpose in the beginning, since that would have affected your responses. In case you do not feel comfortable with this and wish to withdraw your data or delete your responses, you may contact the researcher for the same. I also collected some data regarding your personality and your usual preference for visual or verbal stimuli. This was done to prevent these variables from affecting my results. People with some personality traits like openness to experience (imaginative, creative, preference for novelty) are more likely to feel awe since they are open to a wide range of emotions. Whether one generally prefers reading or seeing visuals can also impact our responses to photos and narratives. Thus, the final scale measured these preferences to statistically control for them. You have made a valuable contribution to the field of psychology by helping us better understand the powerful emotion of awe! You can apply what you have learnt to your daily life by seeking out awe experiences which improve your well-being. This study shows you that there are various ways to do this- reading narratives, seeing pictures or videos that evoke vastness and humility are one way to do this! that evoke vastness and humility or seeing pictures or videos which do the same. If you are interested in obtaining the results of the study or wish to have certain doubts clarified you can contact 7710035657 or email me at janeausten282@gmail.com.  Thank you for participating and taking an important first step in unraveling the potent mysteries of awe!"

function End()
{
    return (<div style={{padding: "10%"}}>
            <Typography variant="body1"> {msg} </Typography>
        </div>)
}

export default End;